### ISSUE TITLE
Customize `durationHistogramsBuckets`

### ISSUE THREAD

**Issue by leandrosantos89** [bfmatei/apollo-prometheus-exporter#14]
The default value of the histogram duration buckets (`durationHistogramsBuckets`) has to many intervals, because of this we are generating a big amount of metrics and we would need a huge infrastructure to handle with this. After some tests, we figure out a way to solve the problem: to customize the `durationHistogramsBuckets` in `createPrometheusExporterPlugin`. What do you think about that? This is possible?

**Comment by bfmatei** [comment]
Thanks for the feedback! I'll update the plugin with a way to customize the buckets. I hope to release it by the end of this week.
