### ISSUE TITLE
Support apolo server v4

### ISSUE THREAD

**Issue by febarbosa182** [bfmatei/apollo-prometheus-exporter#42]
Support the new Apollo Server V4
https://github.com/apollographql/apollo-server/blob/main/packages/server/CHANGELOG.md

**Comment by glensc** [comment]
seems release was made, so this issue can be closed?
- https://github.com/bfmatei/apollo-prometheus-exporter/pull/43

**Comment by rgeyer** [comment]
Oopsie, yep, sure can!

**Comment by glensc** [comment]
can you publish github release?

v2.1.1 listed as latest:
- https://github.com/bfmatei/apollo-prometheus-exporter/releases

**Comment by glensc** [comment]
@rgeyer ^^
