### ISSUE TITLE
Support to Node version 12

### ISSUE THREAD

**Issue by rodrigomageste** [bfmatei/apollo-prometheus-exporter#7]
Hey man, your lib is awesome.

I'm trying to use it in my project, but nullish coalescing operator (`??`) and optional chaining operator (`? .`) seems not work in Node 12.

I made some modifications in the code (basically I changed these operators) and now seems work. Do you intend to support Node 12?

**Comment by tclass** [comment]
I'm also interested in that, have the exact same problem

**Comment by rodrigomageste** [comment]
I can send a PR with my modifications if @bfmatei wants. Like I said, it's very simple, I just changed the operators (`??` and `?.`) mentioned above.

**Comment by bfmatei** [comment]
Sorry for the long waiting. Unfortunately I had a medical condition that kept me away from personal projects lately.

Can you please test v1.2.0 and confirm it is working properly?

Thanks!

**Comment by rodrigomageste** [comment]
It worked perfectly, I already tested it here. Thanks a lot @bfmatei!

**Comment by bfmatei** [comment]
No worries!

Closing this now.
